---
version: 1

auth:
  swagger_token_url: https://some.domain.tld/api/oidc/token
  id_providers: {}
    # some_oidc_provider_here:
    #   type: jwks
    #   issuer_regex: '^https://some.domain.tld$'
    #   jwks_endpoint: https://some.domain.tld/jwks.json
    #   introspection_enabled: true
    #   introspection_endpoint: https://some.domain.tld/api/oidc/introspection
    #   keyid_enabled: false
    #   keyid_endpoint: https://localhost/not/enabled
  incoming:
    clients: {}
      # some_api_client:
      #   contact: some.user@domain.tld
      #   memo: This is just some API client
      #   provider: some_oidc_provider_here
      #   claims:
      #     client_id: some_api_client_id_here
      #   acls:
      #     - section_regex: '^widgets$'
      #       permissions: ['*', 'create']
    api_keys: {}
      # some_key:
      #   contact: some.user@domain.tld
      #   memo: This is just some API key
      #   algo: argon2
      #   hash: '$argon2id$v=19$m=65536,t=3,p=4$tWmX...'
      #   acls:
      #     - section_regex: '^widgets$'
      #       permissions: ['*', 'create']
  outgoing:
    clients: {}
      # some_outbound_api_client:
      #   contact: some.user@domain.tld
      #   memo: This is just some API client
      #   provider: some_oidc_provider_here
      #   grant_type: client_credentials
      #   client_id: some_outgoing_client_id_here
      #   client_secret: # stored in secrets

a2a:
  director_url: http://localhost:10010
  director:
    host: localhost
    port: 10010
    agents:
      widgets: http://localhost:10020
  agents:
    widgets:
      host: localhost
      port: 10020
      mcp_url: http://localhost:8001/mcp/
  llm_provider:
    name: ollama/deepseek-r1:8b
    # base_url: http://1.2.3.4:11434/v1

logging:
  level: DEBUG
  loggers:
    "httpcore":
      level: INFO
  # NOTE: these determine what will be logged as the client IP address; the
  #   first header that matches will be used, so order matters!
  client_host_headers: []
    #- X-Real-IP
    #- X-Forwarded-For

tasks:
  name: nmt-fastapi-a2a
  backend: sqlite
  sqlite_filename: ./huey.sqlite
