name: install-deps
description: Install Python dependencies (Poetry + project extras)
inputs:
  python-version:
    description: 'Python version to set up (e.g. 3.12)'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip

    - name: Install Poetry
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Fetch and install nmt-fastapi-library
      shell: bash
      run: |
        test ! -d ../nmt-fastapi-library || rm -rf ../nmt-fastapi-library
        git clone https://github.com/not-mt/nmt-fastapi-library.git ../nmt-fastapi-library

    - name: Re-install docstring_parser_fork
      shell: bash
      run: |
        docstring_parser_version=$(pip freeze | grep -i docstring_parser== | sed -e 's/==/ /' | awk '{print $2}')
        docstring_parser_fork_version=$(pip freeze | grep -i docstring_parser_fork== | sed -e 's/==/ /' | awk '{print $2}')
        pip uninstall -y docstring_parser_fork docstring_parser
        pip install docstring_parser==$docstring_parser_version
        pip install docstring_parser_fork==$docstring_parser_fork_version
