name: install-deps
description: Install Python dependencies (Poetry + project extras)
inputs:
  python-version:
    description: 'Python version to set up (e.g. 3.12)'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip

    - name: Install Poetry
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Fetch and install nmt-fastapi-library
      shell: bash
      run: |
        test ! -d ../nmt-fastapi-library || rm -rf ../nmt-fastapi-library
        git clone https://github.com/not-mt/nmt-fastapi-library.git ../nmt-fastapi-library
        pip install ../nmt-fastapi-library
