name: Continuous Integration

on:
  push:
    branches:
      - '**'  # all branches
  pull_request:

jobs:
  ci:
    runs-on: self-hosted
    steps:
      # download source for this repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # install dependencies from common template
      - name: Install common dependencies
        uses: ./.github/actions/install-deps
        with:
          python-version: '3.12'

      # install the package for this repo
      - name: Install package
        run: |
          poetry install

      # run the same pre-commit hooks that developers run locally
      - name: Run pre-commit checks
        run: |
          mkdir .local
          pre-commit run --all-files

      # upload coverage to Codecov
      - name: Upload coverage to Codecov (main/PR only)
        uses: codecov/codecov-action@v5
        if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
        with:
          files: .local/coverage
          fail_ci_if_error: true
