name: Continuous Integration

on:
  push:
    branches:
      - '**'  # all branches
  pull_request:

jobs:
  lint:
    # only run for pushes
    if: github.event_name != 'pull_request'
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.11
          - 3.12
          - 3.13
      # max-parallel: 2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Poetry / pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-${{ matrix.python-version }}-

      - name: Install common dependencies
        uses: ./.github/actions/install-deps
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          poetry install

      - name: Fix docstring_parser packages inside Poetry venv
        uses: ./.github/actions/fix-docstring-parser

      - name: Run linter tasks
        run: |
          poetry run invoke lint
