name: Common

on:
  workflow_call:  # makes it reusable
    inputs:
      python-version:
        required: true
        type: string

jobs:
  setup:
    runs-on: self-hosted
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          test ! -d ../nmt-fastapi-library || rm -rf ../nmt-fastapi-library
          git clone https://github.com/not-mt/nmt-fastapi-library.git \
            ../nmt-fastapi-library
          pip install ../nmt-fastapi-library
