name: Main branch CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  lint:
    # only run for a merged pull request or for direct pushes
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Poetry / pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-${{ matrix.python-version }}-

      - name: Install common dependencies
        uses: ./.github/actions/install-deps
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package
        run: |
          poetry install

      - name: Fix docstring_parser packages inside Poetry venv
        uses: ./.github/actions/fix-docstrings

      - name: Run all pre-commit checks
        run: |
          poetry run pre-commit run --all-files

      - name: Upload coverage to Codecov (main/PR only)
        uses: codecov/codecov-action@v5
        with:
          files: .local/coverage
          fail_ci_if_error: true
